/*
We have just updated the main.tf file in this directory with a new resource block. Add a new output variable with the following specifications:
Output Variable Name: welcome_message
Value: content of the resource called welcome
*/
resource "random_pet" "my-pet" {

  length    = var.length 
}

output "pet-name" {
	
	value = random_pet.my-pet.id
	description = "Record the value of pet ID generated by the random_pet resource"
}

resource "local_file" "welcome" {
    filename = "/root/message.txt"
    content = "Welcome to the Jungle."
}

output "welcome_message" {
  value = local_file.welcome.content
}